# PlayStation Vita build (VITA-4). Included from the root CMakeLists.txt when the VitaSDK toolchain
# file is in use (VITA is set by $VITASDK/share/vita.toolchain.cmake). It defines the Vita targets
# itself and the root file returns right after, so none of the desktop targets are configured.
# For now it builds the startup path only (VITA-6); the real sources are switched on by later items.

set(WOWEE_PLATFORM_VITA ON)
add_compile_definitions(WOWEE_PLATFORM_VITA=1)

include("$ENV{VITASDK}/share/vita.cmake" REQUIRED)

# Everything below cannot or should not build for the Vita. The root file returns before it would
# be configured, but the cache values are set so a later shared include cannot switch them on.
set(WOWEE_BUILD_TESTS OFF CACHE BOOL "" FORCE)
set(WOWEE_ENABLE_TRACY OFF CACHE BOOL "" FORCE)
set(WOWEE_ENABLE_AMD_FSR2 OFF CACHE BOOL "" FORCE)
set(WOWEE_ENABLE_AMD_FSR3_FRAMEGEN OFF CACHE BOOL "" FORCE)
set(WOWEE_BUILD_AMD_FSR3_RUNTIME OFF CACHE BOOL "" FORCE)
# Off for now; the 32-bit cleanup (VITA-5) makes it possible to turn it back on.
set(WOWEE_WARNINGS_AS_ERRORS OFF CACHE BOOL "" FORCE)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

set(WOWEE_VITA_TITLEID "WOWE00001" CACHE STRING "Vita title ID (9 characters)")

# -g is required: crash symbolization needs the unstripped ELF of the same build
# (docs/vita/DEV_SETUP.md section 6). CPU flags (armv7-a+simd, NEON, hard float, cortex-a9) are
# already the compiler defaults, so no -mcpu/-mfpu.
foreach(lang C CXX)
    set(CMAKE_${lang}_FLAGS "${CMAKE_${lang}_FLAGS} -O2 -g -ffunction-sections -fdata-sections")
endforeach()
set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -Wl,--gc-sections")

set(WOWEE_VITA_SRC_DIR ${CMAKE_CURRENT_LIST_DIR}/../../src/platform/vita)
set(WOWEE_VITA_RES_DIR ${CMAKE_CURRENT_LIST_DIR}/../../resources/vita)

# The startup path (VITA-6): the shared main.cpp up to the point where the Application would be
# built, with the logger and the config paths it uses, plus the Vita platform layer. The rest of
# the tree joins as the headless core (VITA-9) and the Vulkan-free UI (VITA-12) land.
set(WOWEE_ROOT_DIR ${CMAKE_CURRENT_LIST_DIR}/../..)
set(WOWEE_VITA_HEAP_MB 192 CACHE STRING "newlib heap in MB (compile-time: newlib reads it before main)")
set(WOWEE_VITA_STACK_MB 4 CACHE STRING "main thread stack in MB")

# include/core/version.hpp, generated the way the root file does (cmake/GitVersion.cmake).
set(WOWEE_VERSION_HEADER ${CMAKE_BINARY_DIR}/generated/core/version.hpp)
set(WOWEE_VERSION_SCRIPT_ARGS
    -DSRC_DIR=${WOWEE_ROOT_DIR}
    -DIN_FILE=${WOWEE_ROOT_DIR}/include/core/version.hpp.in
    -DOUT_FILE=${WOWEE_VERSION_HEADER}
    -P ${WOWEE_ROOT_DIR}/cmake/GitVersion.cmake)
execute_process(COMMAND ${CMAKE_COMMAND} ${WOWEE_VERSION_SCRIPT_ARGS})
add_custom_target(wowee_version ALL
    COMMAND ${CMAKE_COMMAND} ${WOWEE_VERSION_SCRIPT_ARGS}
    BYPRODUCTS ${WOWEE_VERSION_HEADER}
    COMMENT "Resolving version from git"
    VERBATIM)

# The platform layer every Vita executable that uses the logger or threads links (VITA-6, VITA-8,
# VITA-42): the startup path, the log sink, the thread budget and the thread-safe-statics guards.
set(WOWEE_VITA_PLATFORM_SOURCES
    ${WOWEE_VITA_SRC_DIR}/vita_main.cpp
    ${WOWEE_VITA_SRC_DIR}/vita_cxa_guard.cpp
    ${WOWEE_VITA_SRC_DIR}/vita_env.cpp
    ${WOWEE_VITA_SRC_DIR}/vita_log_sink.cpp
    ${WOWEE_VITA_SRC_DIR}/vita_threads.cpp)

# The Vita's own declarations of the renderer classes (VITA-52, ADR-001): copies of upstream's rendering/
# headers with every Vulkan declaration removed, generated by tools/vita/gen_shadow.py. A target that
# compiles sources from src/core or src/ui links this FIRST so `#include "rendering/renderer.hpp"` resolves
# there. Nothing links it yet: those sources need VITA-12 first (tools/vita/shadow_check.sh lists what is left).
add_library(wowee_vita_shadow INTERFACE)
target_include_directories(wowee_vita_shadow BEFORE INTERFACE ${WOWEE_ROOT_DIR}/cmake/vita/shadow)

# Everything a Vita executable of ours needs at link time, in one place so no target can miss one
# (VITA-47). Call it for every executable that links wowee_core or the platform layer.
function(wowee_vita_executable target)
    add_dependencies(${target} wowee_version)
    target_include_directories(${target} PRIVATE ${WOWEE_ROOT_DIR}/include ${CMAKE_BINARY_DIR}/generated)
    target_compile_definitions(${target} PRIVATE
        WOWEE_VITA_HEAP_MB=${WOWEE_VITA_HEAP_MB} WOWEE_VITA_STACK_MB=${WOWEE_VITA_STACK_MB})
    target_link_libraries(${target} PRIVATE pthread
        SceIofilemgr_stub SceLibKernel_stub SceSysmodule_stub SceNet_stub SceNetCtl_stub ScePower_stub)

    # GCC 15's __gthread_active_p() tests a weak reference to pthread_cancel; without this
    # std::thread throws "Enable multithreading to use std::thread: Not owner" (see
    # tools/vita/depcheck/CMakeLists.txt).
    target_link_options(${target} PRIVATE -Wl,-u,pthread_cancel)

    # pthread-embedded gives a std::thread a 32 KB stack; vita_threads.cpp wraps pthread_create to
    # raise it (VITA-8). Every Vita executable that starts threads needs both.
    target_link_options(${target} PRIVATE -Wl,--wrap=pthread_create)

    # sceUserMainThreadStackSize (vita_main.cpp) is read by the loader from the ELF, but nothing in
    # the program references it, so --gc-sections removed it and the main thread kept its 256 KB
    # stack (measured on hardware, VITA-8). -u keeps it.
    target_link_options(${target} PRIVATE -Wl,-u,sceUserMainThreadStackSize)
endfunction()

add_executable(wowee
    ${WOWEE_ROOT_DIR}/src/main.cpp
    ${WOWEE_ROOT_DIR}/src/core/logger.cpp
    ${WOWEE_ROOT_DIR}/src/core/config_paths.cpp
    ${WOWEE_VITA_PLATFORM_SOURCES})
wowee_vita_executable(wowee)

# wowee_core (VITA-47): the renderer-free core (auth, network, game, pipeline, ...), built from the
# same sources as on the desktop. The silent AudioEngine replaces miniaudio (no backend yet, VITA-29)
# and Warden is stubbed (cmake/wowee_core.cmake). Nothing links it into the VPK yet: the headless
# client (VITA-48) will. wowee_core_link_check is an ELF that links every object of it, so a symbol
# the core needs and cannot find fails the build here.
add_compile_definitions(GLM_ENABLE_EXPERIMENTAL GLM_FORCE_DEPTH_ZERO_TO_ONE)
set(WOWEE_CORE_NULL_AUDIO ON)
set(WOWEE_CORE_LIBS ssl crypto z pthread)
include(${CMAKE_CURRENT_LIST_DIR}/../wowee_core.cmake)
target_compile_definitions(wowee_core_objects PUBLIC WOWEE_VITA_HEAP_MB=${WOWEE_VITA_HEAP_MB})
target_sources(wowee_core_link_check PRIVATE ${WOWEE_VITA_PLATFORM_SOURCES})
wowee_vita_executable(wowee_core_link_check)

# wowee_client (VITA-52): the application shell (src/core, src/ui, addons) over the core, with the Vita's window
# and renderer skeletons.
include(${CMAKE_CURRENT_LIST_DIR}/wowee_client.cmake)

# wowee_headless (VITA-48): the console client on the core, its own VPK so wowee.vpk keeps working.
# The Vita has no command line: it reads WOWEE_HEADLESS_* from ux0:data/wowee/env.txt. The client's
# own expansion tables (about 300 KB, not game data) ship in the VPK under Data/expansions.
set(WOWEE_VITA_HEADLESS_TITLEID "WOWH00001" CACHE STRING "Title ID of the headless client (9 characters)")
add_executable(wowee_headless
    ${WOWEE_ROOT_DIR}/tools/headless/main.cpp
    ${WOWEE_ROOT_DIR}/tools/headless/headless_client.cpp
    ${WOWEE_VITA_PLATFORM_SOURCES})
target_link_libraries(wowee_headless PRIVATE wowee_core ${WOWEE_CORE_LIBS})
wowee_vita_executable(wowee_headless)

set(WOWEE_VITA_HEADLESS_TABLES)
file(GLOB _expansion_dirs LIST_DIRECTORIES true ${WOWEE_ROOT_DIR}/Data/expansions/*)
foreach(dir ${_expansion_dirs})
    if(NOT IS_DIRECTORY ${dir})
        continue()
    endif()
    get_filename_component(_id ${dir} NAME)
    file(GLOB _tables ${dir}/*.json)
    foreach(table ${_tables})
        get_filename_component(_name ${table} NAME)
        if(NOT _name STREQUAL "manifest.json")
            list(APPEND WOWEE_VITA_HEADLESS_TABLES ${table} Data/expansions/${_id}/${_name})
        endif()
    endforeach()
endforeach()

# UNSAFE: extended memory and some sysmodules.
vita_create_self(eboot.bin wowee UNSAFE)
vita_create_vpk(wowee.vpk ${WOWEE_VITA_TITLEID} eboot.bin
    VERSION "00.01"
    NAME "WoWee"
    FILE ${WOWEE_VITA_RES_DIR}/sce_sys/icon0.png sce_sys/icon0.png
         ${WOWEE_VITA_RES_DIR}/sce_sys/livearea/contents/bg.png sce_sys/livearea/contents/bg.png
         ${WOWEE_VITA_RES_DIR}/sce_sys/livearea/contents/startup.png sce_sys/livearea/contents/startup.png
         ${WOWEE_VITA_RES_DIR}/sce_sys/livearea/contents/template.xml sce_sys/livearea/contents/template.xml)

# vita_create_vpk is a macro that accumulates these across calls: without the reset the second VPK
# gets the first one's files (a duplicate icon0.png, a build error) and its title ID.
unset(VITA_PACK_VPK_FLAGS)
unset(VITA_MKSFOEX_FLAGS)
unset(resources)
vita_create_self(headless.bin wowee_headless UNSAFE)
vita_create_vpk(wowee_headless.vpk ${WOWEE_VITA_HEADLESS_TITLEID} headless.bin
    VERSION "00.01"
    NAME "WoWee Headless"
    FILE ${WOWEE_VITA_RES_DIR}/sce_sys/icon0.png sce_sys/icon0.png
         ${WOWEE_VITA_RES_DIR}/sce_sys/livearea/contents/bg.png sce_sys/livearea/contents/bg.png
         ${WOWEE_VITA_RES_DIR}/sce_sys/livearea/contents/startup.png sce_sys/livearea/contents/startup.png
         ${WOWEE_VITA_RES_DIR}/sce_sys/livearea/contents/template.xml sce_sys/livearea/contents/template.xml
         ${WOWEE_VITA_HEADLESS_TABLES})
