// GENERATED by tools/vita/gen_shadow.py (opaque entry in HANDWRITTEN). DO NOT EDIT.
#pragma once
namespace wowee::rendering {
class AmdFsr3Runtime {
public:
    AmdFsr3Runtime();
    ~AmdFsr3Runtime();
};
}  // namespace wowee::rendering
