// GENERATED by tools/vita/gen_shadow.py (hand-written entry in HANDWRITTEN). DO NOT EDIT.
#pragma once
// The Vita's texture object as the rest of the client sees it (VITA-12). include/rendering/gpu_texture.hpp aliases it
// to VkTexture on the Vulkan renderer; here it is the vitaGL renderer's own class, defined where that renderer is.
namespace wowee::rendering {
class GpuTexture;
void reportBlockUploadTally();
}  // namespace wowee::rendering
