// GENERATED by tools/vita/gen_shadow.py from include/rendering/lightning.hpp. DO NOT EDIT.
// The Vita's copy: every declaration that mentions Vulkan is removed (ADR-001, VITA-52).
#pragma once

#include <glm/glm.hpp>
#include <vector>

namespace wowee {
namespace rendering {

class Camera;

/**
 * Lightning system for thunder storm effects
 *
 * Features:
 * - Random lightning strikes during rain
 * - Screen flash effect
 * - Procedural lightning bolts with branches
 * - Thunder timing (light then sound delay)
 * - Intensity scaling with weather
 */
class Lightning {
public:
    Lightning();
    ~Lightning();

    void shutdown();
    void recreatePipelines();
    /// The two pipelines both initialize() and recreatePipelines() need.

    void update(float deltaTime, const Camera& camera);

    // Control
    void setEnabled(bool enabled);
    [[nodiscard]] bool isEnabled() const { return enabled; }

    void setIntensity(float intensity);  // 0.0 - 1.0 (affects frequency)
    [[nodiscard]] float getIntensity() const { return intensity; }

    // Trigger manual strike (for testing or scripted events)
    void triggerStrike(const glm::vec3& position);

private:
    struct LightningBolt {
        glm::vec3 startPos;
        glm::vec3 endPos;
        float lifetime;
        float maxLifetime;
        std::vector<glm::vec3> segments;  // Bolt path
        std::vector<glm::vec3> branches;  // Branch points
        float brightness;
        bool active;
    };

    struct Flash {
        float intensity;  // 0.0 - 1.0
        float lifetime;
        float maxLifetime;
        bool active;
    };

    void generateLightningBolt(LightningBolt& bolt);
    void generateBoltSegments(const glm::vec3& start, const glm::vec3& end,
                             std::vector<glm::vec3>& segments, int depth = 0);
    void updateBolts(float deltaTime);
    void updateFlash(float deltaTime);
    void spawnRandomStrike(const glm::vec3& cameraPos);


    bool enabled = true;
    float intensity = 0.5f;  // Strike frequency multiplier

    // Timing
    float strikeTimer = 0.0f;
    float nextStrikeTime = 0.0f;

    // Active effects
    std::vector<LightningBolt> bolts;
    Flash flash;

    // Vulkan objects

    // Bolt pipeline + dynamic buffer

    // Flash pipeline + static quad buffer

    // Configuration
    static constexpr int MAX_BOLTS = 3;
    static constexpr float MIN_STRIKE_INTERVAL = 2.0f;
    static constexpr float MAX_STRIKE_INTERVAL = 8.0f;
    static constexpr float BOLT_LIFETIME = 0.15f;  // Quick flash
    static constexpr float FLASH_LIFETIME = 0.3f;
    static constexpr float STRIKE_DISTANCE = 200.0f;  // From camera
    static constexpr int MAX_SEGMENTS = 64;
    static constexpr float BRANCH_PROBABILITY = 0.3f;
};

} // namespace rendering
} // namespace wowee
