// GENERATED by tools/vita/gen_shadow.py from include/rendering/mount_dust.hpp. DO NOT EDIT.
// The Vita's copy: every declaration that mentions Vulkan is removed (ADR-001, VITA-52).
#pragma once

#include <glm/glm.hpp>
#include <vector>

namespace wowee {
namespace rendering {

class Camera;

class MountDust {
public:
    MountDust();
    ~MountDust();

    void shutdown();
    void recreatePipelines();
    /// The pipeline state both initialize() and
    /// recreatePipelines() need, described once.

    // Spawn dust particles at mount feet when moving on ground
    void spawnDust(const glm::vec3& position, const glm::vec3& velocity, bool isMoving);

    void update(float deltaTime);

private:
    struct Particle {
        glm::vec3 position;
        glm::vec3 velocity;
        float lifetime;
        float maxLifetime;
        float size;
        float alpha;
    };

    static constexpr int MAX_DUST_PARTICLES = 300;
    std::vector<Particle> particles;

    // Vulkan objects

    // Dynamic mapped buffer for particle vertex data (updated every frame)

    std::vector<float> vertexData;
    float spawnAccum = 0.0f;
};

} // namespace rendering
} // namespace wowee
