// GENERATED by tools/vita/gen_shadow.py from include/rendering/quest_marker_renderer.hpp. DO NOT EDIT.
// The Vita's copy: every declaration that mentions Vulkan is removed (ADR-001, VITA-52).
#pragma once

#include <glm/glm.hpp>
#include <cstdint>
#include <vector>
#include <unordered_map>


namespace wowee {
namespace pipeline { class AssetManager; }
namespace rendering {

class Camera;

/**
 * Renders quest markers as billboarded sprites above NPCs
 * Uses BLP textures from Interface\GossipFrame\
 */
class QuestMarkerRenderer {
public:
    QuestMarkerRenderer();
    ~QuestMarkerRenderer();

    void shutdown();
    void recreatePipelines();

    /**
     * Add or update a quest marker at a position
     * @param guid NPC GUID
     * @param position World position (NPC base position)
     * @param markerType 0=available(!), 1=turnin(?), 2=incomplete(?)
     * @param boundingHeight NPC bounding height (optional, default 2.0f)
     * @param grayscale 0 = full colour, 1 = desaturated grey (trivial/low-level quests)
     */
    void setMarker(uint64_t guid, const glm::vec3& position, int markerType,
                   float boundingHeight = 2.0f, float grayscale = 0.0f);


    /**
     * Clear all markers
     */
    void clear();

    /**
     * Render all quest markers (call after world rendering, before UI)
     * @param cmd Command buffer to record into
     * @param perFrameSet Per-frame descriptor set (set 0, contains camera UBO)
     * @param camera Camera for billboard calculation (CPU-side view matrix)
     */

private:
    struct Marker {
        glm::vec3 position;
        int type; // 0=available, 1=turnin, 2=incomplete
        float boundingHeight = 2.0f;
        float grayscale = 0.0f; // 0 = colour, 1 = desaturated (trivial quests)
    };

    std::unordered_map<uint64_t, Marker> markers_;

    // Vulkan context

    // Pipeline

    // Descriptor resources for per-material texture (set 1)

    // Textures: available, turnin, incomplete

    // Quad vertex buffer

    void createQuad();
    void loadTextures(pipeline::AssetManager* assetManager);
    void createDescriptorResources();
};

} // namespace rendering
} // namespace wowee
