// GENERATED by tools/vita/gen_shadow.py (opaque entry in HANDWRITTEN). DO NOT EDIT.
#pragma once
namespace wowee::rendering {
class RtScene {
public:
    RtScene();
    ~RtScene();
};
}  // namespace wowee::rendering
