// GENERATED by tools/vita/gen_shadow.py (opaque entry in HANDWRITTEN). DO NOT EDIT.
#pragma once
namespace wowee::rendering {
class ScreenCapture {
public:
    ScreenCapture();
    ~ScreenCapture();
};
}  // namespace wowee::rendering
