// GENERATED by tools/vita/gen_shadow.py (opaque entry in HANDWRITTEN). DO NOT EDIT.
#pragma once
namespace wowee::rendering {
class SunShafts {
public:
    SunShafts();
    ~SunShafts();
};
}  // namespace wowee::rendering
