// GENERATED by tools/vita/gen_shadow.py (opaque entry in HANDWRITTEN). DO NOT EDIT.
#pragma once
namespace wowee::rendering {
class SwimEffects {
public:
    SwimEffects();
    ~SwimEffects();
};
}  // namespace wowee::rendering
