#!/usr/bin/env python3
"""Generate the Vita's shadow headers from upstream's own (VITA-52, ADR-001).

    tools/vita/gen_shadow.py            # (re)write cmake/vita/shadow/rendering/*.hpp
    tools/vita/gen_shadow.py --check    # exit 1 if a committed shadow header differs from what upstream's
                                        # header would produce now (run after every upstream sync)

The Vita build puts cmake/vita/shadow/ first on the include path, so the 28 sources outside
rendering/ that `#include "rendering/renderer.hpp"` get the copy below, which has every declaration that
mentions Vulkan deleted and everything else exactly as upstream wrote it. Generated, never edited by
hand: a header that is not generated cannot be checked against upstream, and upstream adds methods
often. When a method a source needs is missing, the Vita compile names it; the fix is in the Vita
implementation (src/rendering/gl/), not in the copy.

Per-header extra drops (types and includes that are GPU-only but contain no Vulkan token) are in HEADERS.
"""
import os
import sys

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'collision_check'))
import make_shadow  # noqa: E402

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
SRC = os.path.join(ROOT, 'include', 'rendering')
DST = os.path.join(ROOT, 'cmake', 'vita', 'shadow', 'rendering')

COMMON = ['shadow_params.hpp', 'ShadowParamsSet']

# header -> extra tokens to drop (besides the Vulkan ones and COMMON)
HEADERS = {
    'renderer.hpp': ['GPUPerFrameData'],
    'character_renderer.hpp': ['MaterialDescriptorKey', 'MaterialDescriptorKeyHash'],
    'wmo_renderer.hpp': [],
    'm2_renderer.hpp': ['ParticleGroupKey', 'ParticleGroupKeyHash'],
    'minimap.hpp': [],
    'character_preview.hpp': [],
    'post_process_pipeline.hpp': ['AllocatedImage'],
    'lens_flare.hpp': [],
    'quest_marker_renderer.hpp': [],
    'footprint_renderer.hpp': [],
    'loading_screen.hpp': [],
    'weather.hpp': [],
    'terrain_renderer.hpp': [],
    'water_renderer.hpp': [],
    'skybox.hpp': [],
    'celestial.hpp': [],
    'starfield.hpp': [],
    'clouds.hpp': [],
    'aux_swapchain.hpp': [],
    'world_map/world_map_facade.hpp': [],
    'm2_model_classifier.hpp': [],
    'sky_system.hpp': [],
    # Pulled in by the real animation_controller.hpp / footstep_driver.hpp (VITA-52).
    'charge_effect.hpp': [],
    'mount_dust.hpp': [],
    'lightning.hpp': [],
    # Members of Renderer (unique_ptr), so ~Renderer needs the types complete (VITA-52).
}

BANNER = '''// GENERATED by tools/vita/gen_shadow.py from include/rendering/{name}. DO NOT EDIT.
// The Vita's copy: every declaration that mentions Vulkan is removed (ADR-001, VITA-52).
'''

# Headers that must not be reachable on the Vita at all: including one is an error that names the
# item that removes the dependency, instead of a missing vulkan.h.
POISON = {
    'vk_context.hpp': 'rendering/vk_context.hpp included in a Vita build: a Vulkan type leaked outside rendering/ (VITA-12)',
}


# Headers the Vita defines itself instead of stripping: the real one names a Vulkan class. Kept here, in the generator,
# so they are checked like the others (--check) and live in one place.
def _opaque(cls):
    # A GPU-only class the shared code only holds by unique_ptr (Renderer's members): the Vita needs the type complete
    # for ~Renderer and nothing else. If shared code calls a method, the Vita compile says so; add it here.
    return (f"// GENERATED by tools/vita/gen_shadow.py (opaque entry in HANDWRITTEN). DO NOT EDIT.\n#pragma once\n"
            f"namespace wowee::rendering {{\nclass {cls} {{\npublic:\n    {cls}();\n    ~{cls}();\n}};\n}}  // namespace wowee::rendering\n")


HANDWRITTEN = {
    'swim_effects.hpp': _opaque('SwimEffects'),
    'volumetric_fog.hpp': _opaque('VolumetricFog'),
    'sun_shafts.hpp': _opaque('SunShafts'),
    'screen_capture.hpp': _opaque('ScreenCapture'),
    'rt_scene.hpp': _opaque('RtScene'),
    'rt_lighting.hpp': _opaque('RtLighting'),
    'render_graph.hpp': _opaque('RenderGraph'),
    'overlay_system.hpp': _opaque('OverlaySystem'),
    'hiz_system.hpp': _opaque('HiZSystem'),
    'grass_renderer.hpp': _opaque('GrassRenderer'),
    'amd_fsr3_runtime.hpp': _opaque('AmdFsr3Runtime'),
    'gpu_texture.hpp': """// GENERATED by tools/vita/gen_shadow.py (hand-written entry in HANDWRITTEN). DO NOT EDIT.
#pragma once
// The Vita's texture object as the rest of the client sees it (VITA-12). include/rendering/gpu_texture.hpp aliases it
// to VkTexture on the Vulkan renderer; here it is the vitaGL renderer's own class, defined where that renderer is.
namespace wowee::rendering {
class GpuTexture;
void reportBlockUploadTally();
}  // namespace wowee::rendering
""",
}


# Vita-only members added to a generated class (VITA-18): header -> (class, public declarations, private declarations).
# The stripped class has lost its Vulkan methods (initialize(VkContext*...), render(VkCommandBuffer...)), so the GL renderer
# needs a place to declare its own entry points and its private state. They go at the start of the public / private section
# of the class; the implementations are in src/rendering/gl/.
EXTRA_MEMBERS = {
    'terrain_renderer.hpp': ('TerrainRenderer', """    // ---- Vita (VITA-18): the GL half, src/rendering/gl/terrain_renderer_gl.cpp ----
    bool glInitialize(pipeline::AssetManager* assets);
    /// Draw the loaded chunks. `scene` carries the camera matrices, the light and the fog.
    void glRender(const gl::SceneParams& scene);
    [[nodiscard]] bool glReady() const;
""", """    struct Gl;
    std::unique_ptr<Gl> gl_;
"""),
}

EXTRA_MEMBERS['m2_renderer.hpp'] = ('M2Renderer', """    // ---- Vita (VITA-19): the GL half, src/rendering/gl/m2_renderer_gl.cpp ----
    bool glInitialize(pipeline::AssetManager* assets);
    void glRender(const gl::SceneParams& scene);
    [[nodiscard]] bool glReady() const;
    [[nodiscard]] uint32_t glInstanceCount() const;
    /// Gives the collision code an instance (VITA-57) for models that can block.
    void mirrorCollisionInstance(uint32_t id, uint32_t modelId, const glm::mat4& modelMatrix);
""", """    struct Gl;
    std::unique_ptr<Gl> gl_;
""")

EXTRA_MEMBERS['wmo_renderer.hpp'] = ('WMORenderer', """    // ---- Vita (VITA-19): the GL half, src/rendering/gl/wmo_renderer_gl.cpp ----
    bool glInitialize(pipeline::AssetManager* assets);
    void glRender(const gl::SceneParams& scene);
    [[nodiscard]] bool glReady() const;
    [[nodiscard]] uint32_t glInstanceCount() const;
    /// Builds collision for the buildings near `focus` (a worker thread) and drops it for the far ones.
    void glUpdateCollision(const glm::vec3& focus);
    struct Gl;
""", """    std::unique_ptr<Gl> gl_;
""")

EXTRA_MEMBERS['water_renderer.hpp'] = ('WaterRenderer', """    // ---- Vita (VITA-21): the GL half, src/rendering/gl/water_renderer_gl.cpp ----
    bool glInitialize();
    void glRender(const gl::SceneParams& scene, float timeSeconds);
    [[nodiscard]] bool glReady() const;
    void rebuildGlMesh(int64_t key, int tileX, int tileY, uint32_t wmoId);
    struct Gl;
""", """    std::unique_ptr<Gl> gl_;
""")

EXTRA_MEMBERS['character_renderer.hpp'] = ('CharacterRenderer', """    // ---- Vita (VITA-20): the GL half, src/rendering/gl/character_renderer_gl.cpp ----
    bool glInitialize(pipeline::AssetManager* assets);
    void glRender(const gl::SceneParams& scene);
    [[nodiscard]] bool glReady() const;
""", """    struct Gl;
    std::unique_ptr<Gl> gl_;
""")

EXTRA_INCLUDES = {
    'character_renderer.hpp': '#include "rendering/gl/scene_params.hpp"\n',
    'water_renderer.hpp': '#include "rendering/gl/scene_params.hpp"\n',
    'wmo_renderer.hpp': '#include "rendering/gl/scene_params.hpp"\n',
    'm2_renderer.hpp': '#include "rendering/gl/scene_params.hpp"\n',
    'terrain_renderer.hpp': '#include "rendering/gl/scene_params.hpp"\n',
}


def inject(name, text):
    if name not in EXTRA_MEMBERS:
        return text
    cls, pub, priv = EXTRA_MEMBERS[name]
    import re as _re
    m = _re.search(r'^class ' + cls + r'\b[^;{]*\{\s*\npublic:\n', text, _re.M)
    assert m, f'{name}: class {cls} with a public: section not found'
    text = text[:m.end()] + pub + text[m.end():]
    m = _re.search(r'^private:\n', text[m.end():], _re.M)
    assert m, f'{name}: no private: section after the class'
    # re-find in the whole text (offsets shifted)
    start = _re.search(r'^class ' + cls + r'\b', text, _re.M).start()
    pm = _re.search(r'^private:\n', text[start:], _re.M)
    pos = start + pm.end()
    text = text[:pos] + priv + text[pos:]
    inc = EXTRA_INCLUDES.get(name, '')
    if inc:
        first = _re.search(r'^#include', text, _re.M)
        text = text[:first.start()] + inc + text[first.start():]
    return text


def generate():
    out = {}
    for name, extra in HEADERS.items():
        text = open(os.path.join(SRC, name)).read().split('\n')
        token = make_shadow.make_token(COMMON + extra)
        out[name] = inject(name, BANNER.format(name=name) + '\n'.join(make_shadow.strip(text, token)))
    out.update(HANDWRITTEN)
    for name, msg in POISON.items():
        out[name] = f'// GENERATED by tools/vita/gen_shadow.py. DO NOT EDIT.\n#pragma once\n#error "{msg}"\n'
    return out


def main():
    check = '--check' in sys.argv
    stale = []
    for name, text in generate().items():
        path = os.path.join(DST, name)
        if check:
            have = open(path).read() if os.path.exists(path) else None
            if have != text:
                stale.append(name)
        else:
            os.makedirs(os.path.dirname(path), exist_ok=True)
            open(path, 'w').write(text)
    if check:
        if stale:
            print('shadow headers out of date (run tools/vita/gen_shadow.py):', ', '.join(stale))
            sys.exit(1)
        print('shadow headers match upstream')


if __name__ == '__main__':
    main()
