// GENERATED by tools/vita/gen_shadow.py from include/rendering/footprint_renderer.hpp. DO NOT EDIT.
// The Vita's copy: every declaration that mentions Vulkan is removed (ADR-001, VITA-52).
#pragma once

#include <array>
#include <cstdint>
#include <string>
#include <unordered_map>
#include <vector>

#include <glm/glm.hpp>


namespace wowee {
namespace pipeline { class AssetManager; }
namespace rendering {

class Camera;
class Renderer;

enum class FootprintFallback : uint8_t {
    BIPED,
    HOOF,
    PAW,
    CLAW,
    CLOVEN
};

/**
 * Short-lived ground decals spawned by authored M2 footfall events.
 * CreatureModelData supplies the original-client mask and physical dimensions.
 */
class FootprintRenderer {
public:
    FootprintRenderer() = default;
    ~FootprintRenderer();

    void shutdown();
    void recreatePipelines();

    void update(float deltaTime);
    void clear();
    void spawn(const std::string& modelName, const glm::vec3& basePosition,
               float yawRadians, bool leftFoot, FootprintFallback fallback);

private:
    struct Profile {
        uint8_t textureIndex = 0;
        float length = 1.0f;
        float width = 0.8f;
    };

    struct Print {
        glm::vec3 position{0.0f};
        float yaw = 0.0f;
        float length = 1.0f;
        float signedWidth = 0.8f;
        float age = 0.0f;
        uint8_t textureIndex = 0;
    };

    static constexpr size_t kTextureCount = 6;

    Renderer* owner_ = nullptr;

    std::unordered_map<std::string, Profile> profilesByPath_;
    std::unordered_map<std::string, Profile> profilesByBasename_;
    std::vector<Print> prints_;

    bool createPipeline();
    bool createDescriptorResources();
    bool createQuad();
    bool loadFootprintData(pipeline::AssetManager* assetManager);
    [[nodiscard]] Profile resolveProfile(const std::string& modelName, FootprintFallback fallback) const;
    [[nodiscard]] float resolveFloorHeight(const glm::vec3& position) const;
};

} // namespace rendering
} // namespace wowee
