// GENERATED by tools/vita/gen_shadow.py from include/rendering/loading_screen.hpp. DO NOT EDIT.
// The Vita's copy: every declaration that mentions Vulkan is removed (ADR-001, VITA-52).
#pragma once

#include <string>
#include <vector>

struct SDL_Window;

namespace wowee {
namespace rendering {


class LoadingScreen {
public:
    LoadingScreen();
    ~LoadingScreen();

    bool initialize();
    void shutdown();

    void selectRandomImage();

    // Render the loading screen with progress bar and status text (pure ImGui)
    void render();

    // Draw loading screen as ImGui overlay (call within an existing ImGui frame).
    // Used during warmup to overlay loading screen on top of the rendered world.
    void renderOverlay();
    /// The fullscreen window both draws open, and its background blit.
    void beginBackdrop(const char* windowName, float screenW, float screenH);

    void setProgress(float progress) { loadProgress = progress; }
    void setStatus(const std::string& status) { statusText = status; }
    void setZoneName(const std::string& name) { zoneName = name; }

    // Must be set before initialize() for Vulkan texture upload
    void setSDLWindow(SDL_Window* win) { sdlWindow = win; }

private:
    bool loadImage(const std::string& path);

    SDL_Window* sdlWindow = nullptr;

    // Vulkan texture for background image

    std::vector<std::string> imagePaths;
    int currentImageIndex = 0;

    float loadProgress = 0.0f;
    std::string statusText = "Loading...";
    std::string zoneName;

    int imageWidth = 0;
    int imageHeight = 0;
};

} // namespace rendering
} // namespace wowee
